### ISSUE TITLE
Please remove, or strike through, or archive to an Archive section the following  Projects which have not had activity in years and/or only use deprecated versions of Phalcon 1.x, 2.x

### ISSUE THREAD

**Issue by mbrowniebytes** [sergeyklay/awesome-phalcon#120]
Per Contribution Guidelines, "To remove from the list: Open an issue"  

Please remove, or strike through, or archive to an Archive section the following 
Projects which have not had activity in years and/or only use deprecated versions of Phalcon 1.x, 2.x  

While this will make the Phalcon Awesome list smaller, there will be more usable Projects listed for the current Phalcon 3.x and 4.x branches  

List with Projects ~~striked through~~  
https://github.com/mbrowniebytes/awesome-phalcon

Projects to remove, or strike through, or archive:  

## Application Skeleton

*Various application skeletons.*

* [Lightning](https://github.com/zxz054321/lightning/) - Lightning is a high performance framework with elegant syntax that sits on top of Phalcon.
* [nest](https://github.com/nexik/nest) - Phalcon SOLID Bootstrap for Rapid Application Development
* [phalanx](https://github.com/Swader/phalanx) - A starter app with Phalcon Framework and Angular
* [Phalcon Boilerplate](https://github.com/mikegioia/phalcon-boilerplate) - Template for building large-scale Phalcon Applications
* [Phalcon Framework App](https://github.com/eristoddle/phalcon-gumby2-experiment) - A project currently using Phalcon Framework and Gumby 2 for RAD
* [Phalcon HMVC Skeleton](https://github.com/zekiunal/PhalconHMVCSkeletonApplication) - Phalcon HMVC Skeleton with Mustache
* [Phalcon Jumpstart](https://github.com/nguyenducduy/phalcon-jumpstart) - Fast development web apps with CRUD code generator
* [Phalcon Module Skeleton](https://github.com/ovr/phalcon-module-skeleton) - Application template for building beauty applications on Phalcon Framework
* [phalcon.angular.bootstrap](https://github.com/zhegwood/phalcon.angular.bootstrap) - Boilerplate for a non single page implementation of Angular, Phalcon, and Bootstrap
* [PhalconPHP-Setup-Example](https://github.com/ewartx/PhalconPHP-Setup-Example) - Phalcon Framework + Grunt + Composer + Bower
* [Solid Layer](https://github.com/solid-layer/solid-layer) - A framework/large wrapper built under Phalcon Framework
* [phalconMvc](https://github.com/kcloze/phalconMvc) - a simple Phalcon skeleton with sub controller,cli,mvc +service

## Authentication & OAuth

*Libraries for implementing authentications schemes.*

* [phalcon-oauth2-server](https://github.com/nueko/phalcon-oauth2-server) - Phalcon wrapper for oAuth2 [thephpleague/oauth2-server](https://github.com/thephpleague/oauth2-server)

## CMS & Blogs

*Content management systems & blogs.*

* [blog](https://github.com/duythien/blog) - Blog project with multi-lingual support
* [phalconBlog](https://github.com/eristoddle/phalconBlog) - A blog using the Phalcon Framework
* [PhalconEye](https://github.com/PhalconEye/phalconeye) - PhalconEye CMS
* [Talon](https://github.com/adamdama/Talon) - CMS built on Phalcon Framework
* [Vegas CMF](https://github.com/vegas-cmf) - Vegas CMF for Phalcon Framework

## Command Line

*Command line applications & tools.*

* [phalcon_cron](https://github.com/temafey/phalcon_cron) - Cron manager library based on Phalcon Framework
* [php-cli-app-phalcon](https://github.com/jeteokeeffe/php-cli-app-phalcon) - Command Line Application built using Phalcon Framework

## Dashboard

*Admin Panels & Dashboards.*

* [dasshy](https://github.com/phalcon-orphanage/dasshy) - Statistics dashboard with Mongo/Phalcon

## Debug

*Debug & profiling tools.*

* [PDW](https://github.com/jymboche/phalcon-debug-widget) - Frontend Debugger for Phalcon Applications
* [Phalcon Console](https://github.com/vanchelo/phalcon-console) - AJAX console to execute PHP code in the browser with light, the ability to save the last code execution
* [Phalcon Whoops](https://github.com/whoops-php/phalcon) - Integrating [Whoops](https://filp.github.io/whoops/) with Phalcon

## DI

*Dependency Injection.*

* [phalcon-autoload-services](https://github.com/JimmDiGrizli/phalcon-autoload-services) - Components for automatic registration services in Dependency Injection
* [phalcon-service-loader](https://github.com/serebro/phalcon-service-loader) - Service loader for Phalcon Framework
* [pidic](https://github.com/phalette/pidic) - Nette Dependency Injection/Container for Phalcon

## Docs

*Libraries for doc generate & management.*

* [kolibri](https://github.com/philippgerard/kolibri) - A Phalcon based wiki software with simplicity in mind
* [phaldoc](https://github.com/Riu/phaldoc) - Create, translate and control changes in documentation for Phalcon & others projects

## Events

*Event management.*

* [Phact](https://github.com/wandersonwhcr/phact) -  A Simple Event Propagation with Phalcon Framework

## Forms

*Libraries for working with forms.*

* [Phalcon Preserve Post](https://github.com/JREAM/phalcon-preserve-post) - Preserve Form Data after a `POST` and redirect
* [phalcon-form-decorators](https://github.com/Michal-St/phalcon-form-decorators) - Form decorators to Phalcon Framework
* [phalconCssForm](https://github.com/Zheness/phalconCssForm) - Generate a form with a CSS Framework (Bootstrap, Foundation, Pure, etc.)
* [Superform](https://github.com/encodez/superform) - Simple way to create and validate Phalcon 2 form inspired by the Laravel request

## i18n

*List of i18n and l10n libraries and services.*

* [Phalcon Translate Service](https://github.com/stanislav-web/phalcon-translate) - Phalcon Translate Service. Simple way to translate your custom part of templates
* [Phalcon Translation Module](https://github.com/uLow/phalcon-translate) - Phalcon Translation Module. Easy way to have translations for your projects. Includes volt integration.

## Mail

*Mail services.*

* [Phalcon Mailer](https://github.com/vanchelo/phalcon-mailer) - Phalcon Mailer Service
* [Phalcon Mailer](https://github.com/phalcon-ext/mailer) - Mailer component wrapper over SwiftMailer for Phalcon Framework
* [phalconphp-mandrill](https://bitbucket.org/tartan/phalconphp-mandrill/src) - Mandrill wrapper for Phalcon Framework
* [sendmail](https://github.com/duythien/sendmail) - Sending Confirmation Emails with Phalcon Framework and Swift

## Media

*Libraries for manipulating images & other media.*

* [nova](https://github.com/nohatssir/nova) - A media manager project in PHP and Phalcon Framework
* [Phalcon File Uploader](https://github.com/stanislav-web/phalcon-uploader) - Handling and downloading files for Phalcon projects. Allowed multiple files, filters etc

## Miscellaneous

*These libraries were placed here because none of the other categories seemed to fit*

* [Phalcon Enterprise](https://github.com/techpivot/phalcon-enterprise) - Provides extended enterprise functionality for the Phalcon framework
* [phalcon-recaptcha](https://github.com/kahurangitama/phalcon-recaptcha) - Minimalist wrapper with which you can easily integrate reCAPTCHA
* [phalcon-widget](https://github.com/serebro/phalcon-widget) - Widgets for Phalcon apps
* [PhalconBlacklist](https://github.com/touhonoob/PhalconBlacklist) - PHP IP/CIDR Blacklist Library Built With Phalcon + MySQL
* [Phalcony](https://github.com/ovr/phalcony) - Library for expansion the base functional of Phalcon Framework

## Networking

*Libraries for working with various layers of the network*

* [phalcon-expressive](https://github.com/theDisco/phalcon-expressive) - Phalcon 2 integration for Zend Expressive

## ORM

*Libraries that implement Object-Relational Mapping or datamapping techniques.*

* [phalcon-mssql](https://github.com/fishjerky/phalcon-mssql) - A Phalcon Framework MSSQL PDO db adapter

## Provisioning

*Tools for provisioning a system for a Phalcon application.*

* [ansible-phalcon-role](https://github.com/sarrubia/ansible-phalcon-role) - Ansible Role to install Phalcon Framework in Debian/Ubuntu

## RESTful

*Representational state transfer.*

* [Phalcon Development Boards](https://github.com/stanislav-web/Phalcon-development) - An example development of the REST application by Phalcon Framework
* [Phalcon REST](https://github.com/redound/phalcon-rest) - Phalcon REST Library
* [Phalcon Rest JWT](https://github.com/nerfe/phalconphp-rest-jwt-acl) - This project uses Phalcon Micro Framework for REST API with JWT and ACL
* [Phalcon Restful Webservice](https://github.com/praswicaksono/phalcon-restful-webservice) - Base project for creating powerful webservice based on Phalcon Framework
* [phalcon-api-oauth2](https://github.com/goors/phalcon-api-oauth2) - Full Phalcon REST API example with is own OAuth2 server
* [phalcon-rest-boilerplate](https://github.com/redound/phalcon-rest-boilerplate) - Phalcon REST Boilerplate
* [phalcon-json-api](https://github.com/gte451f/phalcon-json-api) - A reference application combining Phalcon + JSON:API + Composer
* [PhalconRest](https://github.com/cmoore4/phalcon-rest) - A Base project for APIs using the Phalcon Framework
* [phest](https://github.com/ovide/phest) - REST API library for Phalcon
* [php-hmac-rest-api](https://github.com/jeteokeeffe/php-hmac-rest-api) - PHP HMAC Restful API that uses Phalcon Micro Application
* [rest-seed](https://github.com/michaelkrone/rest-seed) - Scaffold a REST API Application Phalcon (multi module), Angular and Bootstrap (using Yeoman, Bower and Grunt)

## Scaffolding

*Various scaffolding tools.*

* [generator-phalcon](https://github.com/michaelkrone/generator-phalcon) - Yeoman generator for Phalcon Multi-Module Applications
* [phalcon-bootstrap](https://github.com/JimmDiGrizli/phalcon-bootstrap) - Bootstrap component for a quick start developing applications on Phalcon Framework

## Searching

*Searching tools & libraries.*

* [phalcon-datatables](https://github.com/m1ome/phalcon-datatables) - Phalcon adapter for DataTables
* [phalcon-elasticsearch](https://github.com/ovr/phalcon-elasticsearch) - Phalcon + Elastic
* [Searcher](https://github.com/stanislav-web/Searcher) - Database searcher for Phalcon Framework

## Shopping

*Shopping carts and online store services.*

* [phalcon_cart](https://github.com/uno-de-piera/phalcon_cart) - Complete cart system for Phalcon Framework
* [phasty](https://github.com/chaban/phasty) - Shopping Cart on Phalcon Framework
* [Cashier](https://github.com/duythien/cashier) - Phalcon cashier
* [Yona E-commerce](https://github.com/alexander-torosh/yona-ecommerce) - E-commerce CMF based on Phalcon Framework

## SMS

*SMS services & libraries.*

* [Multiple SMS Sender factory](https://github.com/stanislav-web/phalcon-sms-factory) - Phalcon SMS Factory

## Talks

*Conferences, Chats, Forums, etc..*

* [phalcon-chat](https://github.com/sintsov/phalcon-chat) - Sample classic chat development using Phalcon Framework
* [phalcon-tip](https://github.com/duythien/phalcon-tip) - The source for code Phalcon Tip website

## Templating

*Libraries and tools for templating.*

* [jade-phalcon](https://github.com/kylekatarnls/jade-phalcon) - Jade Template Engine for Phalcon Framework
* [phalcon-xslt-view-engine](https://github.com/racztiborzoltan/phalcon-xslt-view-engine) - Adapter to use XSLT as templating engine for Phalcon Framework

## Validators

*ORM and Forms validators.*

* [Phalcon Validators](https://github.com/renatoneto/phalcon-validators) - Extra validators for Phalcon Framework
* [phalswag](https://github.com/tomi20v/phalswag) - Validate request input against swagger config in Phalcon Framework
* [PHP Request Validator](https://github.com/progsmile/request-validator) - Easy PHP validation with the Phalcon support
* [zvps-phalcon-validators](https://github.com/zVPS/zvps-phalcon-validators) - Additional form and data validators extending the inbuilt Phalcon validate interface

## Web Tools

*Web tools & libraries.*

* [Password Manager](https://github.com/mrspartak/phalconPasswordManager) - Password manager for selfuse
* [URL-Shortener](https://github.com/blackbunny/Url-Shortener) - Simple Fast Url-Shortener application

# Server Applications

* [perfect-php-vagrant](https://github.com/ovr/perfect-php-vagrant) - Web development Vagrant machine with PHP + Phalcon/Lynx/Zephir, Nginx, Node+Bower/Gulp/Grunt
* [phalcon-ci-installer](https://github.com/techpivot/phalcon-ci-installer) - Composer integration for PHP applications to install the Phalcon framework as an extension in the PHP runtime for various hosted CI services

**Comment by sergeyklay** [comment]
@mbrowniebytes It makes sense. We have no problem shrinking the list. Could you submit the path?

**Comment by mbrowniebytes** [comment]
Created a pull request for
1st commit striked through the old projects
2nd commit removed the old projects

**Comment by sergeyklay** [comment]
Fixed. Thank you for contributing!
