### ISSUE TITLE
Please Add My Project - yassinrais/sakura-panel

### ISSUE THREAD

**Issue by yassinrais** [sergeyklay/awesome-phalcon#129]
Hello Teams ! 
Can you please add **[Sakura-Panel](https://github.com/yassinrais/sakura-panel)** to the list of Application Skeleton

thankw

**Comment by CameronHall** [comment]
@yassinrais please create a PR

**Comment by yassinrais** [comment]
Okey , i will do it ! 
thanks

**Comment by yassinrais** [comment]
I Pull request , but the test was failed
 can you please investigate it

thanks
