### ISSUE TITLE
Please Add PhalconTool

### ISSUE THREAD

**Issue by corentin-begne** [sergeyklay/awesome-phalcon#138]
Hi,
Can you add my library to the list pls, just updated to phalcon 5 and php 8 it could be helpfull.
https://github.com/corentin-begne/phalconTool

**Comment by niden** [comment]
Please issue a PR with the tool under the relevant category :)

**Comment by corentin-begne** [comment]
@niden Done! :)

**Comment by Jeckerson** [comment]
Thanks!
