### ISSUE TITLE
Please add xgettext-volt to this list

### ISSUE THREAD

**Issue by dschissler** [sergeyklay/awesome-phalcon#43]
I created [xgettext-webird](https://github.com/perchlayer/xgettext-webird) for gettext string extraction for Volt templates.  Its written in Node.js but its part of the Phalcon ecosystem and there is no other existing tool for this functionality.  I think that this project should be included in an `other` section.

**Comment by sergeyklay** [comment]
:+1:

**Comment by sergeyklay** [comment]
tomorrow
