### ISSUE TITLE
Please add PhalconCMS to this list

### ISSUE THREAD

**Issue by aihunter666** [sergeyklay/awesome-phalcon#80]
[PhalconCMS](https://github.com/KevinJay/PhalconCMS)  is  a  blog  system.  Could  you  add  this project  to this list? thanks.

PhalconCMS:    https://github.com/KevinJay/PhalconCMS

**Comment by sergeyklay** [comment]
@KevinJay Could you please send a PR?

**Comment by aihunter666** [comment]
ok

**Comment by valVk** [comment]
There have to be some kind of respect to the peoples who do not know, I even doubt whether it Chinese or Japanese. Could README.md be in English?

Thanks

**Comment by dsouksavatd** [comment]
the content should not containing sexual or pornographic links ^^

**Comment by valVk** [comment]
LOOOOOOOOOOOL

**Comment by aihunter666** [comment]
@valVk It's chinese.  I will update  in Englist tomorrow. Thanks

**Comment by sergeyklay** [comment]
@KevinJay Thanks

**Comment by valVk** [comment]
@KevinJay and please take a look to the dsouksavatd's comment.

@sergeyklay Do you warned about link to the adult resource in proposed repository? )

Thanks

**Comment by sergeyklay** [comment]
@valVk What do you mean? Can you elaborate on that?

**Comment by mizterp** [comment]
@KevinJay Always use example.com for fake/example URLs.. not xxx(dot)com :rofl:

**Comment by aihunter666** [comment]
@mizterp @valVk @dsouksavatd  I'm sorry.  I really don't know xxx(dot)com is real website.  
and thanks @sergeyklay update it for me.
thanks all.
